config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :products

  root "pages#home"

  # type-of-request URL => controller#action
  get "/home" => "pages#home"
  get "/house" => "pages#home"


  # NEWS_POST RESOURCE
  resources :news_posts

  # # new
  # get "/news_posts/new" => "news_posts#new"

  # # create
  # post "/news_posts" => "news_posts#create"

  # # index
  # get "/news_posts" => "news_posts#index"

  # # show
  # get "/news_posts/:id" => "news_posts#show", as: :news_post

  # # edit
  # get "/news_posts/:id/edit" => "news_posts#edit"

  # # update
  # patch "/news_posts/:id" => "news_posts#update"

  # # destroy
  # delete "/news_posts/:id" => "news_posts#destroy"

  # Products Resource

end

app/models/news_post.rb
class NewsPost < ActiveRecord::Base

  validates :title, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles


  # find a role with the name "admin"
  # find the user
  # user.roles < role

  def add_role(role)
    self.roles << role
  end

  def add_role_by_name(role_name)
    role = Role.find_by(name: role_name)
    self.add_role(role)
  end

  def is_role?(role)
    self.roles.include?(role)
  end

  def is_role_by_name?(role_name)
    role = Role.find_by(name: role_name)
    self.is_role?(role)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/news_posts_controller.rb
class NewsPostsController < ApplicationController

  before_action :deny_access_for_non_admins, except: [:index, :show, :index_ajax]

  def index
    @news_posts = NewsPost.all

    respond_to do |format|
      format.html
      format.json { render json: @news_posts }
    end
  end

  def show
    @news_post = NewsPost.find(params[:id])
  end

  def new
    @news_post = NewsPost.new
  end

  def create
    @news_post = NewsPost.new(news_post_params)

    if @news_post.save
      # do something - go back to the index
      redirect_to "/news_posts"
    else
      render 'new'
    end
  end

  def edit
    @news_post = NewsPost.find params[:id]
  end

  def update
    @news_post = NewsPost.find params[:id]

    if @news_post.update(news_post_params)
      redirect_to "/news_posts"
    else
      render 'edit'
    end

  end

  def destroy
    @news_post = NewsPost.find params[:id]
    @news_post.destroy

    redirect_to "/news_posts"
  end

  private

    def deny_access_for_non_admins
      if !is_admin?
        redirect_to root_path
      end
    end

    def news_post_params
      params.require(:news_post).permit(:title, :body)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home 
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :discount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_posts_helper.rb
module NewsPostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def is_admin?
    current_user && current_user.is_role_by_name?("admin")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
    <div class="container">
      <div class="logo">
        <%= image_tag "logo.png" %>
      </div>

      <div class="nav">
        <%= link_to "Home", root_path %>
        <%= link_to "News Posts", news_posts_path %>

        <% if user_signed_in? %>
          <%= link_to "Sign out (#{current_user.email})", 
                      destroy_user_session_path, 
                      data: { method: :delete } %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
        <% end %>

      </div>
    </div>

  </div>

  <div id="content">
    <div class="container">
      <%= yield %>
    </div>  
  </div>

  <div id="footer">
    <div class="container">
      Copyright (C) Casey Li, 2015
    </div>
  </div>
  

</body>
</html>

app/views/news_posts/_form.html.erb
<%= form_for @news_post do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/news_posts/edit.html.erb
<h1>Editing News Post</h1>

<%= render "form" %>

app/views/news_posts/index.html.erb
<h1>News Posts</h1>

<p>
  Welcome to the News Posts page.
</p>

<p>
  Number of posts <%= @news_posts.size %>
</p>

<% if is_admin? %>
  <%= link_to "New News Post", new_news_post_path %>
<% end %>


<% @news_posts.each do |news_post| %>
  <div class="news-post">
    <h2><%= news_post.title %></h2>
    <p>
      <%= news_post.body %>
    </p>
    <p>
      <%= link_to "Show Details", news_post  %>

      <% if is_admin? %>
        <%= link_to "Edit Post", edit_news_post_path(news_post) %>
        <%= link_to "Destroy Post", news_post,
                    method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/news_posts/new.html.erb
<h1>Creating a new News Post</h1>

<%= render "form" %>

app/views/news_posts/show.html.erb
<h1>News Post page for ID: <%= @news_post.id %></h1>

<p>
  <b>Title: </b> <%= @news_post.title %>
</p>

<p>
  <b>Body: </b> <%= @news_post.body %>
</p>

<p>
  <b>Created At: </b> <%= @news_post.created_at %>
</p>

<p>
  <b>Updated At: </b> <%= @news_post.updated_at %>
</p>

<%= link_to "Back to News Posts", news_posts_path %>

app/views/pages/home.html.erb
<h1>Welcome to my home page</h1>

<%= link_to "Contact Us For More Information", "#", class: "show-contact-form" %>
<%= link_to "Show me news posts", "#", class: "show-news-posts" %>

<div class="contact-us-message">
  

</div>

<div class="news-posts">
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Discount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.discount %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @product.discount %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>